### ISSUE TITLE
请问学姐（学长）可以把作业放上来嘛，拜托了！

### ISSUE THREAD

**Issue by PommesPeter** [BITXiaBee/Courses#3]
双非学生表示很想看BIT的作业，拜托了！

**Comment by xiabee** [comment]
等考完试我整理一下吧......主要是有些作业实在写的太烂了没脸发（x）

**Comment by PommesPeter** [comment]
> xiabee
> 等考完试我整理一下吧......主要是有些作业实在写的太烂了没脸发（x）

感谢！！！Thank you very much! （有机会可以相互交流学习学习😂
